import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "./header";

const rubik = Rubik({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="h-full selection:bg-teal-500 selection:text-white"
		>
			<body className={`${rubik.className} flex flex-col h-full`}>
				<Header />
				<div className="flex overflow-x-hidden p-5 h-full bg-white">
					{children}
				</div>
			</body>
		</html>
	);
}
